# Autogenerated wrapper script for MAFFT_jll for powerpc64le-linux-gnu-cxx03
export einsi, fftns, fftnsi, ginsi, linsi, mafft, mafft_distance, mafft_einsi, mafft_fftns, mafft_fftnsi, mafft_ginsi, mafft_homologs_rb, mafft_linsi, mafft_nwns, mafft_nwnsi, mafft_profile, mafft_qinsi, mafft_sparsecore_rb, mafft_xinsi, nwns, nwnsi

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("MAFFT")
JLLWrappers.@declare_executable_product(einsi)
JLLWrappers.@declare_executable_product(fftns)
JLLWrappers.@declare_executable_product(fftnsi)
JLLWrappers.@declare_executable_product(ginsi)
JLLWrappers.@declare_executable_product(linsi)
JLLWrappers.@declare_executable_product(mafft)
JLLWrappers.@declare_executable_product(mafft_distance)
JLLWrappers.@declare_executable_product(mafft_einsi)
JLLWrappers.@declare_executable_product(mafft_fftns)
JLLWrappers.@declare_executable_product(mafft_fftnsi)
JLLWrappers.@declare_executable_product(mafft_ginsi)
JLLWrappers.@declare_executable_product(mafft_homologs_rb)
JLLWrappers.@declare_executable_product(mafft_linsi)
JLLWrappers.@declare_executable_product(mafft_nwns)
JLLWrappers.@declare_executable_product(mafft_nwnsi)
JLLWrappers.@declare_executable_product(mafft_profile)
JLLWrappers.@declare_executable_product(mafft_qinsi)
JLLWrappers.@declare_executable_product(mafft_sparsecore_rb)
JLLWrappers.@declare_executable_product(mafft_xinsi)
JLLWrappers.@declare_executable_product(nwns)
JLLWrappers.@declare_executable_product(nwnsi)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        einsi,
        "bin/einsi",
    )

    JLLWrappers.@init_executable_product(
        fftns,
        "bin/fftns",
    )

    JLLWrappers.@init_executable_product(
        fftnsi,
        "bin/fftnsi",
    )

    JLLWrappers.@init_executable_product(
        ginsi,
        "bin/ginsi",
    )

    JLLWrappers.@init_executable_product(
        linsi,
        "bin/linsi",
    )

    JLLWrappers.@init_executable_product(
        mafft,
        "bin/mafft",
    )

    JLLWrappers.@init_executable_product(
        mafft_distance,
        "bin/mafft-distance",
    )

    JLLWrappers.@init_executable_product(
        mafft_einsi,
        "bin/mafft-einsi",
    )

    JLLWrappers.@init_executable_product(
        mafft_fftns,
        "bin/mafft-fftns",
    )

    JLLWrappers.@init_executable_product(
        mafft_fftnsi,
        "bin/mafft-fftnsi",
    )

    JLLWrappers.@init_executable_product(
        mafft_ginsi,
        "bin/mafft-ginsi",
    )

    JLLWrappers.@init_executable_product(
        mafft_homologs_rb,
        "bin/mafft-homologs.rb",
    )

    JLLWrappers.@init_executable_product(
        mafft_linsi,
        "bin/mafft-linsi",
    )

    JLLWrappers.@init_executable_product(
        mafft_nwns,
        "bin/mafft-nwns",
    )

    JLLWrappers.@init_executable_product(
        mafft_nwnsi,
        "bin/mafft-nwnsi",
    )

    JLLWrappers.@init_executable_product(
        mafft_profile,
        "bin/mafft-profile",
    )

    JLLWrappers.@init_executable_product(
        mafft_qinsi,
        "bin/mafft-qinsi",
    )

    JLLWrappers.@init_executable_product(
        mafft_sparsecore_rb,
        "bin/mafft-sparsecore.rb",
    )

    JLLWrappers.@init_executable_product(
        mafft_xinsi,
        "bin/mafft-xinsi",
    )

    JLLWrappers.@init_executable_product(
        nwns,
        "bin/nwns",
    )

    JLLWrappers.@init_executable_product(
        nwnsi,
        "bin/nwnsi",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
